// Product catalogue used to generate src/lib/demoSeed.ts and the SQL seed
// migration. `image` is relative to public/images/. `existing` marks products
// whose photo already shipped with the repo (it is moved into the category
// folder instead of being generated).
export const catalog = [
  /* ------------------------------------------------------------ clothing */
  { cat: 'clothing', slug: 'classic-white-shirt', name: 'پیراهن مردانه کلاسیک سفید', price: 890000, rating: 4.7, stock: 80, existing: 'prod-shirt-1.jpg', desc: 'پیراهن مردانه کلاسیک با یقه رسمی، دوخت مرغوب از پنبه طبیعی ۱۰۰٪' },
  { cat: 'clothing', slug: 'elegant-pink-blouse', name: 'بلوز زنانه شیک صورتی', price: 1200000, rating: 4.8, stock: 60, existing: 'prod-shirt-2.jpg', desc: 'بلوز زنانه طراحی خاص با پارچه نرم و راحت، مناسب مجالس و محل کار' },
  { cat: 'clothing', slug: 'oxford-blue-shirt-men', name: 'پیراهن آکسفورد آبی مردانه', price: 1150000, rating: 4.6, stock: 70, desc: 'پیراهن آکسفورد آبی با پارچه نخی ضخیم، مناسب استایل رسمی و اسمارت‌کژوال' },
  { cat: 'clothing', slug: 'silk-blouse-cream-women', name: 'بلوز ابریشمی زنانه کرم', price: 1750000, rating: 4.8, stock: 45, desc: 'بلوز ابریشمی با درخشش ملایم و لمس لطیف، انتخابی لوکس برای مهمانی‌ها' },
  { cat: 'clothing', slug: 'knit-sweater-gray-men', name: 'پلیور بافت مردانه طوسی', price: 1450000, rating: 4.5, stock: 65, desc: 'پلیور بافت درشت با نخ مرینوس، گرم و سبک برای روزهای سرد' },
  { cat: 'clothing', slug: 'turtleneck-sweater-beige-women', name: 'پلیور یقه اسکی زنانه بژ', price: 1380000, rating: 4.7, stock: 55, desc: 'پلیور یقه اسکی با بافت نرم و فرم‌دهی عالی، مناسب پاییز و زمستان' },
  { cat: 'clothing', slug: 'basic-tshirt-black-men', name: 'تی‌شرت پایه مردانه مشکی', price: 490000, rating: 4.4, stock: 150, desc: 'تی‌شرت نخی پنبه شانه‌زده با یقه گرد و دوخت تقویت‌شده' },
  { cat: 'clothing', slug: 'oversize-tshirt-white-women', name: 'تی‌شرت اورسایز زنانه سفید', price: 560000, rating: 4.5, stock: 130, desc: 'تی‌شرت اورسایز با پارچه سنگین و فرم افتاده، استایل مینیمال روزمره' },
  { cat: 'clothing', slug: 'hoodie-charcoal-men', name: 'هودی مردانه ذغالی', price: 1650000, rating: 4.6, stock: 90, desc: 'هودی سه‌نخ داخل‌کرک با کلاه دو لایه و جیب کانگورویی' },
  { cat: 'clothing', slug: 'hoodie-blush-women', name: 'هودی زنانه صورتی کمرنگ', price: 1590000, rating: 4.7, stock: 85, desc: 'هودی زنانه با رنگ پاستلی و پارچه نرم، راحت برای استفاده روزمره' },
  { cat: 'clothing', slug: 'denim-jacket-men', name: 'ژاکت جین مردانه', price: 2350000, rating: 4.7, stock: 50, desc: 'ژاکت جین کلاسیک با دکمه فلزی و جیب سینه، همیشه در ترند' },
  { cat: 'clothing', slug: 'trench-coat-camel-women', name: 'ترنچ‌کت زنانه شتری', price: 3900000, rating: 4.9, stock: 30, desc: 'ترنچ‌کت بلند با کمربند پارچه‌ای و آستر داخلی، شیک و بادگیر' },
  { cat: 'clothing', slug: 'wool-blazer-navy-men', name: 'کت تک پشمی مردانه سرمه‌ای', price: 4200000, rating: 4.8, stock: 25, desc: 'کت تک پشمی با برش تیلور و آستر ابریشمی، مناسب محافل رسمی' },
  { cat: 'clothing', slug: 'midi-dress-floral-women', name: 'پیراهن میدی گلدار زنانه', price: 2100000, rating: 4.6, stock: 40, desc: 'پیراهن میدی با طرح گل‌های ریز و پارچه ویسکوز خنک' },
  { cat: 'clothing', slug: 'polo-shirt-green-men', name: 'پولوشرت مردانه سبز', price: 850000, rating: 4.4, stock: 110, desc: 'پولوشرت پیکه با یقه ریب و دوخت تمیز، مناسب بهار و تابستان' },
  { cat: 'clothing', slug: 'satin-blazer-black-women', name: 'کت ساتن مشکی زنانه', price: 2950000, rating: 4.8, stock: 35, desc: 'کت ساتن مشکی با برش ساختاریافته و درخشش ظریف، مناسب استایل رسمی و شب' },
  { cat: 'clothing', slug: 'knit-cardigan-cream-women', name: 'ژاکت بافت کرم زنانه', price: 1850000, rating: 4.7, stock: 50, desc: 'ژاکت بافت نرم و سبک با رنگ کرم، مناسب لایه‌سازی در استایل پاییزی' },

  /* --------------------------------------------------------------- pants */
  { cat: 'pants', slug: 'slim-jeans-men', name: 'شلوار جین مردانه اسلیم', price: 1500000, rating: 4.6, stock: 100, existing: 'prod-pants-1.jpg', desc: 'شلوار جین مردانه اسلیم فیت با پارچه کش‌سفارشی و دوام بالا' },
  { cat: 'pants', slug: 'linen-pants-women', name: 'شلوار کتان زنانه', price: 1350000, rating: 4.5, stock: 75, existing: 'prod-pants-2.jpg', desc: 'شلوار کتان زنانه با طراحی مدرن و راحتی فوق‌العاده، مناسب فصل بهار و تابستان' },
  { cat: 'pants', slug: 'straight-jeans-dark-men', name: 'جین راسته مردانه تیره', price: 1620000, rating: 4.6, stock: 95, desc: 'جین راسته با شست‌وشوی تیره و پارچه ۱۲ اونس، فرم ماندگار' },
  { cat: 'pants', slug: 'mom-jeans-light-women', name: 'مام‌جین زنانه آبی روشن', price: 1580000, rating: 4.7, stock: 88, desc: 'مام‌جین فاق بلند با فرم ریلکس و پارچه جین سنگین' },
  { cat: 'pants', slug: 'chino-beige-men', name: 'شلوار چینو مردانه بژ', price: 1290000, rating: 4.5, stock: 105, desc: 'چینو نخی با کمی کشسانی، مناسب استایل اداری و روزمره' },
  { cat: 'pants', slug: 'chino-olive-men', name: 'شلوار چینو مردانه زیتونی', price: 1290000, rating: 4.4, stock: 98, desc: 'چینو زیتونی با برش اسلیم و جیب‌های مورب' },
  { cat: 'pants', slug: 'wide-leg-trousers-black-women', name: 'شلوار دمپا گشاد زنانه مشکی', price: 1700000, rating: 4.8, stock: 70, desc: 'شلوار پارچه‌ای دمپا گشاد با کمر کش و افتادگی زیبا' },
  { cat: 'pants', slug: 'formal-trousers-charcoal-men', name: 'شلوار رسمی مردانه ذغالی', price: 1850000, rating: 4.6, stock: 60, desc: 'شلوار پارچه‌ای رسمی با تای اتوخورده و برش تیلور' },
  { cat: 'pants', slug: 'cargo-pants-khaki-men', name: 'شلوار کارگو مردانه خاکی', price: 1550000, rating: 4.5, stock: 85, desc: 'کارگو با شش جیب کاربردی و پارچه مقاوم' },
  { cat: 'pants', slug: 'cargo-pants-sage-women', name: 'شلوار کارگو زنانه سبز روشن', price: 1490000, rating: 4.6, stock: 78, desc: 'کارگو زنانه با دمپای کش‌دار و جیب‌های بغل' },
  { cat: 'pants', slug: 'jogger-navy-men', name: 'شلوار جاگر مردانه سرمه‌ای', price: 980000, rating: 4.4, stock: 120, desc: 'جاگر سه‌نخ با بند کمر و مچ کش، راحت برای ورزش و خانه' },
  { cat: 'pants', slug: 'jogger-gray-women', name: 'شلوار جاگر زنانه طوسی', price: 950000, rating: 4.5, stock: 115, desc: 'جاگر زنانه با پارچه نرم و جیب زیپ‌دار' },
  { cat: 'pants', slug: 'corduroy-pants-brown-men', name: 'شلوار مخمل کبریتی مردانه قهوه‌ای', price: 1450000, rating: 4.5, stock: 65, desc: 'شلوار مخمل کبریتی با بافت گرم و رنگ‌بندی پاییزی' },
  { cat: 'pants', slug: 'paperbag-pants-cream-women', name: 'شلوار پیپربگ زنانه کرم', price: 1390000, rating: 4.6, stock: 72, desc: 'شلوار پیپربگ با کمر چین‌دار و کمربند هم‌رنگ' },
  { cat: 'pants', slug: 'leggings-black-women', name: 'لگ ورزشی زنانه مشکی', price: 780000, rating: 4.7, stock: 140, desc: 'لگ ورزشی کمر بالا با پارچه ضدعرق و کشسانی چهارجهته' },

  /* ------------------------------------------------------------- glasses */
  { cat: 'glasses', slug: 'luxury-sunglasses-classic', name: 'عینک آفتابی لوکس مدل کلاسیک', price: 1800000, rating: 4.9, stock: 40, existing: 'prod-glasses-1.jpg', desc: 'عینک آفتابی با فریم متالیک و عدسی پلاریزه، محافظت کامل در برابر UV' },
  { cat: 'glasses', slug: 'modern-sunglasses', name: 'عینک آفتابی مدرن', price: 1600000, rating: 4.7, stock: 55, existing: 'prod-glasses-2.jpg', desc: 'عینک آفتابی با طراحی مدرن و رنگ‌های متنوع، مناسب استایل روزمره و مجلسی' },
  { cat: 'glasses', slug: 'aviator-gold-sunglasses', name: 'عینک آفتابی خلبانی طلایی', price: 2150000, rating: 4.8, stock: 45, desc: 'فریم فلزی طلایی با عدسی گرادیانی، طرح خلبانی همیشه‌کلاسیک' },
  { cat: 'glasses', slug: 'round-tortoise-sunglasses', name: 'عینک آفتابی گرد لاک‌پشتی', price: 1750000, rating: 4.6, stock: 50, desc: 'فریم استات با طرح لاک‌پشتی و عدسی قهوه‌ای روشن' },
  { cat: 'glasses', slug: 'cat-eye-sunglasses-black', name: 'عینک آفتابی گربه‌ای مشکی', price: 1890000, rating: 4.7, stock: 48, desc: 'فریم گربه‌ای زنانه با زاویه‌های تیز و عدسی دودی' },
  { cat: 'glasses', slug: 'oversized-sunglasses-brown', name: 'عینک آفتابی بزرگ قهوه‌ای', price: 1950000, rating: 4.6, stock: 42, desc: 'عینک اورسایز با پوشش کامل و فریم استات قهوه‌ای' },
  { cat: 'glasses', slug: 'sport-sunglasses-polarized', name: 'عینک آفتابی ورزشی پلاریزه', price: 2250000, rating: 4.8, stock: 38, desc: 'عینک ورزشی سبک با عدسی پلاریزه و دسته ضدلغزش' },
  { cat: 'glasses', slug: 'wayfarer-sunglasses-navy', name: 'عینک آفتابی ویفرر سرمه‌ای', price: 1690000, rating: 4.5, stock: 60, desc: 'فریم ویفرر کلاسیک با رنگ سرمه‌ای مات' },
  { cat: 'glasses', slug: 'rimless-sunglasses-silver', name: 'عینک آفتابی بدون فریم نقره‌ای', price: 2050000, rating: 4.6, stock: 35, desc: 'طراحی بدون فریم و بسیار سبک با بدنه تیتانیومی' },
  { cat: 'glasses', slug: 'optical-frame-acetate-black', name: 'عینک طبی فریم استات مشکی', price: 1450000, rating: 4.5, stock: 65, desc: 'فریم طبی استات مشکی با لولای فنری و فرم مستطیلی' },
  { cat: 'glasses', slug: 'optical-frame-metal-gold', name: 'عینک طبی فریم فلزی طلایی', price: 1550000, rating: 4.6, stock: 58, desc: 'فریم فلزی نازک طلایی با پل بینی قابل تنظیم' },
  { cat: 'glasses', slug: 'optical-frame-round-clear', name: 'عینک طبی گرد شفاف', price: 1350000, rating: 4.4, stock: 70, desc: 'فریم گرد شفاف با ظاهری مینیمال و امروزی' },
  { cat: 'glasses', slug: 'blue-light-glasses', name: 'عینک محافظ نور آبی', price: 990000, rating: 4.7, stock: 95, desc: 'عینک مخصوص کار با کامپیوتر با پوشش ضد نور آبی' },
  { cat: 'glasses', slug: 'mirrored-sunglasses-blue', name: 'عینک آفتابی آینه‌ای آبی', price: 1780000, rating: 4.5, stock: 52, desc: 'عدسی آینه‌ای آبی با فریم مشکی مات و ظاهری اسپرت' },
  { cat: 'glasses', slug: 'vintage-sunglasses-green', name: 'عینک آفتابی وینتیج سبز', price: 1850000, rating: 4.6, stock: 44, desc: 'طرح وینتیج دهه هفتاد با عدسی سبز و فریم طلایی' },

  /* --------------------------------------------------------------- watch */
  { cat: 'watch', slug: 'luxury-gold-watch', name: 'ساعت مچی لوکس طلایی', price: 4500000, rating: 4.8, stock: 30, existing: 'prod-watch-1.jpg', desc: 'ساعت مچی با بدنه طلایی و بند چرمی، طراحی شیک و کلاسیک برای آقایان' },
  { cat: 'watch', slug: 'sport-watch', name: 'ساعت مچی اسپرت', price: 2800000, rating: 4.6, stock: 45, existing: 'prod-watch-2.jpg', desc: 'ساعت مچی اسپرت با قابلیت ضدآب و طراحی مدرن، مناسب استفاده روزمره و ورزشی' },
  { cat: 'watch', slug: 'classic-leather-watch-brown', name: 'ساعت کلاسیک بند چرم قهوه‌ای', price: 3200000, rating: 4.7, stock: 40, desc: 'ساعت کلاسیک با صفحه سفید و بند چرم طبیعی قهوه‌ای' },
  { cat: 'watch', slug: 'steel-chronograph-watch', name: 'ساعت کرنوگراف استیل', price: 5600000, rating: 4.8, stock: 28, desc: 'کرنوگراف سه‌شمارنده با بدنه استیل ضدزنگ و شیشه سافایر' },
  { cat: 'watch', slug: 'minimal-watch-white-dial', name: 'ساعت مینیمال صفحه سفید', price: 2450000, rating: 4.6, stock: 55, desc: 'طراحی مینیمال بدون عدد با بند مش نقره‌ای' },
  { cat: 'watch', slug: 'diver-watch-blue', name: 'ساعت غواصی آبی', price: 6200000, rating: 4.9, stock: 22, desc: 'ساعت غواصی با مقاومت ۳۰۰ متر و بازل چرخان یک‌طرفه' },
  { cat: 'watch', slug: 'rose-gold-women-watch', name: 'ساعت زنانه رزگلد', price: 3800000, rating: 4.8, stock: 35, desc: 'ساعت ظریف زنانه با روکش رزگلد و نگین‌های دور صفحه' },
  { cat: 'watch', slug: 'mesh-band-watch-silver', name: 'ساعت بند حصیری نقره‌ای', price: 2950000, rating: 4.5, stock: 50, desc: 'بند مش استیل با قفل مگنتی و بدنه فوق‌نازک' },
  { cat: 'watch', slug: 'skeleton-automatic-watch', name: 'ساعت اتوماتیک اسکلتون', price: 7900000, rating: 4.9, stock: 18, desc: 'ساعت اتوماتیک با نمای باز موتور و پشت شیشه‌ای' },
  { cat: 'watch', slug: 'pilot-watch-black', name: 'ساعت خلبانی مشکی', price: 4100000, rating: 4.7, stock: 32, desc: 'ساعت خلبانی با صفحه خوانا، اعداد درشت و بند چرم مشکی' },
  { cat: 'watch', slug: 'digital-sport-watch', name: 'ساعت دیجیتال ورزشی', price: 1450000, rating: 4.4, stock: 80, desc: 'ساعت دیجیتال ضدضربه با کرنومتر، آلارم و نور پس‌زمینه' },
  { cat: 'watch', slug: 'smart-watch-black', name: 'ساعت هوشمند مشکی', price: 5200000, rating: 4.7, stock: 60, desc: 'ساعت هوشمند با نمایشگر AMOLED، پایش ضربان و GPS' },
  { cat: 'watch', slug: 'ceramic-white-watch', name: 'ساعت سرامیکی سفید', price: 4800000, rating: 4.6, stock: 26, desc: 'بدنه و بند سرامیکی سفید، مقاوم در برابر خش و سبک' },
  { cat: 'watch', slug: 'bracelet-watch-women-gold', name: 'ساعت دستبندی زنانه طلایی', price: 3450000, rating: 4.7, stock: 38, desc: 'ساعت دستبندی با صفحه کوچک و بند حلقه‌ای طلایی' },
  { cat: 'watch', slug: 'field-watch-khaki', name: 'ساعت فیلد خاکی', price: 2650000, rating: 4.5, stock: 48, desc: 'ساعت فیلد با بند نظامی نایلونی و صفحه مات ضدبازتاب' },
  { cat: 'watch', slug: 'moonphase-watch-silver', name: 'ساعت مون‌فاز نقره‌ای', price: 6750000, rating: 4.8, stock: 20, desc: 'ساعت نقره‌ای با نمایشگر فاز ماه، صفحه آبی عمیق و بند استیل براق' },
  { cat: 'watch', slug: 'vintage-rectangular-watch', name: 'ساعت مستطیلی وینتیج', price: 3100000, rating: 4.6, stock: 34, desc: 'ساعت مستطیلی با صفحه روشن و بند چرم قهوه‌ای، الهام‌گرفته از طراحی کلاسیک' },

  /* ----------------------------------------------------------------- bag */
  { cat: 'bag', slug: 'leather-handbag-women', name: 'کیف دستی زنانه چرم', price: 2300000, rating: 4.8, stock: 50, existing: 'prod-bag-1.jpg', desc: 'کیف دستی زنانه از چرم طبیعی با طراحی شیک و فضای داخلی جادار' },
  { cat: 'bag', slug: 'mens-messenger-bag', name: 'کیف دوشی مردانه', price: 1900000, rating: 4.5, stock: 65, existing: 'prod-bag-2.jpg', desc: 'کیف دوشی مردانه با چرم باکیفیت و طراحی مینیمال، مناسب محل کار و سفر' },
  { cat: 'bag', slug: 'leather-tote-bag-tan', name: 'کیف توت چرم عسلی', price: 2650000, rating: 4.7, stock: 45, desc: 'کیف توت جادار از چرم عسلی، مناسب کار و دانشگاه' },
  { cat: 'bag', slug: 'crossbody-bag-black', name: 'کیف دوشی زنانه مشکی', price: 1750000, rating: 4.6, stock: 70, desc: 'کیف کراس‌بادی با بند قابل تنظیم و جیب مخفی پشتی' },
  { cat: 'bag', slug: 'mini-shoulder-bag-red', name: 'کیف کوچک دوشی قرمز', price: 1450000, rating: 4.5, stock: 60, desc: 'کیف مینیمال قرمز برای مهمانی و گردش‌های کوتاه' },
  { cat: 'bag', slug: 'leather-backpack-brown', name: 'کوله‌پشتی چرم قهوه‌ای', price: 3100000, rating: 4.8, stock: 38, desc: 'کوله چرم دست‌دوز با محفظه لپ‌تاپ ۱۵ اینچی' },
  { cat: 'bag', slug: 'canvas-backpack-gray', name: 'کوله‌پشتی کتان طوسی', price: 1650000, rating: 4.4, stock: 85, desc: 'کوله کتان سبک با بندهای اسفنجی و جیب بطری' },
  { cat: 'bag', slug: 'laptop-briefcase-black', name: 'کیف اداری لپ‌تاپ مشکی', price: 2850000, rating: 4.7, stock: 40, desc: 'کیف اداری با محفظه ضربه‌گیر لپ‌تاپ و بند شانه‌ای جداشونده' },
  { cat: 'bag', slug: 'clutch-evening-gold', name: 'کلاچ مجلسی طلایی', price: 1350000, rating: 4.6, stock: 55, desc: 'کلاچ مجلسی با بدنه براق طلایی و زنجیر ظریف' },
  { cat: 'bag', slug: 'bucket-bag-cream', name: 'کیف باکت کرم', price: 1890000, rating: 4.5, stock: 48, desc: 'کیف باکت با بند کشویی و آستر پارچه‌ای' },
  { cat: 'bag', slug: 'travel-duffel-bag', name: 'ساک سفری چرم', price: 3950000, rating: 4.8, stock: 25, desc: 'ساک سفری بزرگ با دسته چرمی و بند دوشی قابل تنظیم' },
  { cat: 'bag', slug: 'belt-bag-black', name: 'کیف کمری مشکی', price: 890000, rating: 4.4, stock: 110, desc: 'کیف کمری جمع‌وجور با زیپ ضدآب، مناسب پیاده‌روی و سفر' },
  { cat: 'bag', slug: 'straw-beach-bag', name: 'کیف حصیری ساحلی', price: 1150000, rating: 4.5, stock: 62, desc: 'کیف حصیری دست‌باف با دسته چرمی، مناسب تابستان' },
  { cat: 'bag', slug: 'quilted-chain-bag', name: 'کیف زنجیردار لوزی‌دوزی', price: 2450000, rating: 4.8, stock: 42, desc: 'کیف لوزی‌دوزی با بند زنجیری طلایی و قفل فلزی' },
  { cat: 'bag', slug: 'satchel-bag-navy', name: 'کیف ساچل سرمه‌ای', price: 2150000, rating: 4.6, stock: 44, desc: 'کیف ساچل با دو سگک جلو و فرم ساختاریافته' },

  /* ----------------------------------------------------------- accessory */
  { cat: 'accessory', slug: 'leather-belt-men', name: 'کمربند چرم مردانه', price: 650000, rating: 4.4, stock: 120, existing: 'prod-belt-1.jpg', desc: 'کمربند چرم طبیعی مردانه با سگکی استیل، طراحی شیک و دوام بالا' },
  { cat: 'accessory', slug: 'womens-jewelry-set', name: 'ست جواهری زنانه', price: 3200000, rating: 4.9, stock: 25, existing: 'prod-jewelry-1.jpg', desc: 'ست جواهری زنانه شامل گردنبند و گوشواره با طراحی ظریف و درخشان' },
  { cat: 'accessory', slug: 'leather-belt-brown-classic', name: 'کمربند چرم قهوه‌ای کلاسیک', price: 720000, rating: 4.5, stock: 115, desc: 'کمربند چرم قهوه‌ای با سگک برنجی، مناسب استایل رسمی' },
  { cat: 'accessory', slug: 'womens-thin-belt-black', name: 'کمربند باریک زنانه مشکی', price: 480000, rating: 4.4, stock: 130, desc: 'کمربند باریک زنانه برای مانتو و پیراهن، سگک ظریف طلایی' },
  { cat: 'accessory', slug: 'silk-scarf-patterned', name: 'شال ابریشمی طرح‌دار', price: 1250000, rating: 4.7, stock: 70, desc: 'شال ابریشمی با طرح چاپی رنگی و لبه‌دوزی دستی' },
  { cat: 'accessory', slug: 'wool-scarf-gray', name: 'شال گردن پشمی طوسی', price: 890000, rating: 4.6, stock: 90, desc: 'شال گردن پشمی گرم با بافت ریب و ریشه‌های ظریف' },
  { cat: 'accessory', slug: 'leather-wallet-men', name: 'کیف پول چرم مردانه', price: 760000, rating: 4.6, stock: 125, desc: 'کیف پول جیبی چرم با هشت جای کارت و محفظه اسکناس' },
  { cat: 'accessory', slug: 'card-holder-slim', name: 'جاکارتی باریک چرم', price: 420000, rating: 4.5, stock: 140, desc: 'جاکارتی فوق‌باریک چرم با محافظت RFID' },
  { cat: 'accessory', slug: 'gold-necklace-pendant', name: 'گردنبند طلایی آویزدار', price: 2450000, rating: 4.8, stock: 40, desc: 'گردنبند با زنجیر ظریف طلایی و آویز مینیمال' },
  { cat: 'accessory', slug: 'pearl-earrings', name: 'گوشواره مرواریدی', price: 1650000, rating: 4.8, stock: 55, desc: 'گوشواره با مروارید طبیعی و پایه نقره‌ای آبکاری‌شده' },
  { cat: 'accessory', slug: 'silver-bracelet-chain', name: 'دستبند زنجیری نقره‌ای', price: 1350000, rating: 4.6, stock: 65, desc: 'دستبند زنجیری نقره ۹۲۵ با قفل محکم' },
  { cat: 'accessory', slug: 'mens-signet-ring', name: 'انگشتر مردانه', price: 1850000, rating: 4.5, stock: 48, desc: 'انگشتر مردانه با نگین اونیکس و بدنه استیل' },
  { cat: 'accessory', slug: 'baseball-cap-black', name: 'کلاه بیسبالی مشکی', price: 550000, rating: 4.4, stock: 135, desc: 'کلاه بیسبالی نخی با بند تنظیم فلزی' },
  { cat: 'accessory', slug: 'fedora-hat-beige', name: 'کلاه شاپو بژ', price: 980000, rating: 4.5, stock: 60, desc: 'کلاه شاپو نمدی با نوار مشکی دور تاج' },
  { cat: 'accessory', slug: 'leather-gloves-black', name: 'دستکش چرم مشکی', price: 1150000, rating: 4.6, stock: 75, desc: 'دستکش چرم طبیعی با آستر کشمیر، گرم و انعطاف‌پذیر' },
];

export const categories = [
  { slug: 'clothing', name: 'لباس', icon: 'shirt' },
  { slug: 'pants', name: 'شلوار', icon: 'pants' },
  { slug: 'glasses', name: 'عینک', icon: 'glasses' },
  { slug: 'watch', name: 'ساعت', icon: 'watch' },
  { slug: 'bag', name: 'کیف', icon: 'bag' },
  { slug: 'accessory', name: 'اکسسوری', icon: 'gem' },
];
