/*
 * Regenerates src/lib/demoSeed.ts and supabase/migrations/<ts>_reseed_catalog.sql
 * from scripts/catalog.mjs.
 *
 * Only products whose image file actually exists in public/images/<category>/
 * are emitted, so the catalogue can grow as artwork is added.
 *
 * Usage: npm run seed
 */
import fs from 'fs';
import path from 'path';
import { catalog, categories } from './catalog.mjs';

const root = path.resolve(import.meta.dirname, '..');
const now = Date.now();
const iso = (daysAgo) => new Date(now - daysAgo * 86400000).toISOString();

/* ------------------------------------------------------------- gather -- */

const missing = [];
const products = [];

catalog.forEach((p, i) => {
  const rel = `/images/${p.cat}/${p.slug}.jpg`;
  if (!fs.existsSync(path.join(root, 'public', rel))) {
    missing.push(rel);
    return;
  }
  products.push({
    id: `prod-${p.slug}`,
    name: p.name,
    slug: p.slug,
    description: p.desc,
    price: p.price,
    image_url: rel,
    category_id: `cat-${p.cat}`,
    rating: p.rating,
    stock: p.stock,
    created_at: iso(120 - i),
  });
});

const cats = categories.map((c, i) => ({
  id: `cat-${c.slug}`,
  name: c.name,
  slug: c.slug,
  icon: c.icon,
  created_at: iso(200 - i),
}));

/* ------------------------------------------------- blog posts + reviews  */

const blogPosts = [
  {
    id: 'post-fall-1405-fashion-trends',
    title: 'ترندهای مد پاییز ۱۴۰۵',
    slug: 'fall-1405-fashion-trends',
    excerpt: 'بررسی کامل ترندهای مد پاییز ۱۴۰۵ از رنگ‌های پاییزی تا استایل‌های جدید',
    content:
      'در فصل پاییز ۱۴۰۵ شاهد بازگشت رنگ‌های گرم و خنثی هستیم. تن‌های کرم، قهوه‌ای و نارنجی از رنگ‌های اصلی این فصل هستند. استایل لایه‌ای همچنان محبوب است و می‌توانید با ترکیب پیراهن‌های نازک و کت‌های سبک، یک استایل شیک پاییزی بسازید. شلوارهای گشاد و کتان نیز جای خود را در کمد هر فرد مد‌پسند باز کرده‌اند. در انتخاب اکسسوری، ساعت‌های کلاسیک و عینک‌های آفتابی با فریم بزرگ ترند روز هستند.',
    image_url: '/images/blog-1.jpg',
    author: 'سارا احمدی',
    created_at: iso(9),
  },
  {
    id: 'post-sunglasses-buying-guide',
    title: 'راهنمای انتخاب عینک آفتابی مناسب',
    slug: 'sunglasses-buying-guide',
    excerpt: 'همه چیزهایی که قبل از خرید عینک آفتابی باید بدانید',
    content:
      'انتخاب عینک آفتابی مناسب فقط به مدل و ظاهر آن محدود نمی‌شود. باید به فرم صورت، کیفیت عدسی و محافظت در برابر اشعه UV توجه کنید. برای صورت‌های گرد، عینک‌های زاویه‌دار مناسب‌تر هستند. برای صورت‌های مربعی، عینک‌های گردتر انتخاب بهتری است. عدسی‌های پلاریزه برای رانندگی و فعالیت‌های بیرونی بسیار توصیه می‌شوند. همچنین فریم سبک و راحت برای استفاده طولانی‌مدت اهمیت دارد.',
    image_url: '/images/blog-2.jpg',
    author: 'محمد رضایی',
    created_at: iso(8),
  },
  {
    id: 'post-watch-buying-guide',
    title: 'چگونه ساعت مچی مناسب بخریم؟',
    slug: 'watch-buying-guide',
    excerpt: 'راهنمای جامع خرید ساعت مچی از سبک تا بودجه',
    content:
      'خرید ساعت مچی یکی از مهم‌ترین تصمیمات برای تکمیل استایل است. اولین نکته تعیین بودجه است. ساعت‌های مچی در قیمت‌های متنوعی موجود هستند. بعد از بودجه باید به سبک زندگی خود فکر کنید: ساعت اسپرت برای استفاده روزمره، ساعت کلاسیک برای مجالس و محیط‌های رسمی. جنس بدنه و بند نیز مهم است: استیل ضدزنگ، چرم طبیعی و سرامیک از بهترین گزینه‌ها هستند. در نهایت به اندازه دست و وزن ساعت نیز توجه کنید تا راحتی لازم را داشته باشد.',
    image_url: '/images/blog-3.jpg',
    author: 'نگار کریمی',
    created_at: iso(7),
  },
];

const reviewTemplates = [
  { name: 'علی محمدی', rating: 5, comment: 'کیفیت ساخت عالی و کاملاً مطابق توضیحات. راضی هستم.' },
  { name: 'مریم حسینی', rating: 4, comment: 'کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.' },
  { name: 'حسین کریمی', rating: 5, comment: 'دقیقاً همون چیزی بود که می‌خواستم. پیشنهاد می‌کنم.' },
  { name: 'زهرا نوری', rating: 5, comment: 'بسته‌بندی مرتب و کیفیت بالاتر از انتظار.' },
  { name: 'سینا اکبری', rating: 4, comment: 'در مجموع خوبه، رنگش کمی با عکس تفاوت داره.' },
  { name: 'فاطمه رضایی', rating: 5, comment: 'خرید دوم من از این فروشگاهه، همیشه راضی بودم.' },
  { name: 'نگار صادقی', rating: 4, comment: 'جنس خوبی داره و ارزش خرید داره.' },
  { name: 'رضا تهرانی', rating: 5, comment: 'کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.' },
];

const reviews = [];
products.forEach((p, i) => {
  const count = 2 + (i % 2); // 2 or 3 reviews per product
  for (let j = 0; j < count; j++) {
    const t = reviewTemplates[(i + j * 3) % reviewTemplates.length];
    reviews.push({
      id: `rev-${p.slug}-${j + 1}`,
      product_id: p.id,
      user_id: null,
      name: t.name,
      rating: t.rating,
      comment: t.comment,
      created_at: iso(30 - ((i + j) % 25)),
    });
  }
});

/* --------------------------------------------------------- emit demoSeed */

const ts = `// AUTO-GENERATED by scripts/generate-seed.mjs — do not edit by hand.
// Run \`npm run seed\` after changing scripts/catalog.mjs or adding images.
import type { BlogPost, Category, Product, Review } from './supabase';

export const seedCategories: Category[] = ${JSON.stringify(cats, null, 2)};

export const seedProducts: Product[] = ${JSON.stringify(products, null, 2)};

export const seedBlogPosts: BlogPost[] = ${JSON.stringify(blogPosts, null, 2)};

export const seedReviews: Review[] = ${JSON.stringify(reviews, null, 2)};
`;
fs.writeFileSync(path.join(root, 'src/lib/demoSeed.ts'), ts);

/* ------------------------------------------------------------- emit SQL */

const q = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);

const sql = `/*
# Re-seed catalogue (auto-generated by scripts/generate-seed.mjs)

Replaces categories, products, blog posts and reviews with the full catalogue
(${products.length} products across ${cats.length} categories). Product images live in
public/images/<category>/<slug>.jpg.
*/

DELETE FROM order_items;
DELETE FROM orders;
DELETE FROM cart_items;
DELETE FROM reviews;
DELETE FROM products;
DELETE FROM blog_posts;
DELETE FROM categories;

INSERT INTO categories (name, slug, icon) VALUES
${cats.map((c) => `  (${q(c.name)}, ${q(c.slug)}, ${q(c.icon)})`).join(',\n')}
ON CONFLICT (slug) DO NOTHING;

INSERT INTO products (name, slug, description, price, image_url, category_id, rating, stock) VALUES
${products
  .map(
    (p) =>
      `  (${q(p.name)}, ${q(p.slug)}, ${q(p.description)}, ${p.price}, ${q(p.image_url)}, (SELECT id FROM categories WHERE slug=${q(
        p.category_id.replace('cat-', ''),
      )}), ${p.rating}, ${p.stock})`,
  )
  .join(',\n')}
ON CONFLICT (slug) DO NOTHING;

INSERT INTO blog_posts (title, slug, excerpt, content, image_url, author) VALUES
${blogPosts
  .map((b) => `  (${q(b.title)}, ${q(b.slug)}, ${q(b.excerpt)}, ${q(b.content)}, ${q(b.image_url)}, ${q(b.author)})`)
  .join(',\n')}
ON CONFLICT (slug) DO NOTHING;

INSERT INTO reviews (product_id, name, rating, comment) VALUES
${reviews
  .map(
    (r) =>
      `  ((SELECT id FROM products WHERE slug=${q(r.product_id.replace('prod-', ''))}), ${q(r.name)}, ${r.rating}, ${q(
        r.comment,
      )})`,
  )
  .join(',\n')}
ON CONFLICT DO NOTHING;
`;
fs.writeFileSync(path.join(root, 'supabase/migrations/20260820120000_reseed_full_catalog.sql'), sql);

/* ------------------------------------------------------------- report -- */

const perCat = {};
products.forEach((p) => {
  const c = p.category_id.replace('cat-', '');
  perCat[c] = (perCat[c] || 0) + 1;
});
console.log(`products: ${products.length}/${catalog.length}`, perCat);
if (missing.length) {
  console.log(`missing images (${missing.length}):`);
  missing.forEach((m) => console.log('  ' + m));
}
